version: '3.9'

services:
  db:
    image: mysql:8.0-debian
    container_name: teamspeak-server-manager-db-container
    ports:
      - "33060:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: main